"""Modèles de départ pour les règles simplifiées et les fiches débutants."""

TEMPLATES = {
    "summary": """## But du jeu
Une phrase : comment gagne-t-on la partie ?

## Mise en place
- …

## Déroulement d'un tour
1. …
2. …

## Fin de partie et décompte
- …

## À retenir
- …
""",
    "beginner_guide": """## Avant de commencer
- Durée d'explication : … min
- Joueurs conseillés : …
- Matériel à sortir : …

## Expliquer en 5 minutes
1. Le but du jeu : …
2. Ce qu'on fait à son tour : …
3. Les choix importants : …
4. Comment la partie se termine : …
5. Un exemple concret : …

## Aide-mémoire du tour
- [ ] …
- [ ] …

## Erreurs classiques des nouveaux joueurs
- …

## Partie d'essai conseillée
- …

## Pour que ça se passe bien
- Laisser les débutants jouer en premier.
- Rappeler le but du jeu avant chaque nouvelle phase.
""",
}
