"""Collection : jeux, tags et notes

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 13:35:40.956874
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=True),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_original', sa.String(length=200), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('best_players', sa.String(length=40), nullable=True),
    sa.Column('min_time', sa.Integer(), nullable=True),
    sa.Column('max_time', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Double(), nullable=True),
    sa.Column('bgg_rating', sa.Double(), nullable=True),
    sa.Column('base_game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lent_to', sa.String(length=100), nullable=True),
    sa.Column('lent_since', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('purchase_price_cents', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_place', sa.String(length=100), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_game_id'], ['game.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bgg_id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_ean'), ['ean'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_status'), ['status'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'label')
    )
    op.create_table('game_tag',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    with op.batch_alter_table('game_tag', schema=None) as batch_op:
        batch_op.create_index('ix_game_tag_tag_id', ['tag_id'], unique=False)

    op.create_table('note_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_entry_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_entry_game_id'))

    op.drop_table('note_entry')
    with op.batch_alter_table('game_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_game_tag_tag_id')

    op.drop_table('game_tag')
    op.drop_table('tag')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_status'))
        batch_op.drop_index(batch_op.f('ix_game_ean'))

    op.drop_table('game')
    # ### end Alembic commands ###
