"""Vidéos de règles et fiches de règles

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 14:38:20.281455
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'kind')
    )
    with op.batch_alter_table('rule_sheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_sheet_game_id'), ['game_id'], unique=False)

    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('channel', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'youtube_id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_game_id'))

    op.drop_table('video')
    with op.batch_alter_table('rule_sheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_sheet_game_id'))

    op.drop_table('rule_sheet')
    # ### end Alembic commands ###
